import { createContext, useContext, useState, useEffect } from "react";

// תיקון: הוספנו null כדי למנוע את שגיאת ה-TypeScript
// בתוך LanguageContext.jsx
export const LanguageContext = createContext({
  language: 'he',
  changeLanguage: () => {},
  t: {}
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    // טעינת השפה מהזיכרון של הדפדפן, ברירת מחדל עברית
    return localStorage.getItem("language") || "he";
  });

  const changeLanguage = (newLang) => {
    setLanguage(newLang);
    localStorage.setItem("language", newLang);
  };

  // שליפת המילים המתאימות מהמילון
  const t = translations[language] || translations.he;

  // עדכון כיוון האתר (RTL/LTR) בכל פעם שהשפה משתנה
  useEffect(() => {
    const dir = t.dir || (language === "he" ? "rtl" : "ltr");
    document.documentElement.dir = dir;
    document.documentElement.lang = language;
  }, [language, t.dir]);

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};


  // ─── Translation Dictionary ────────────────────────────────────────────────
  // מכאן והלאה זה המילון הענק שלך (he, en, ru) - אל תגע בו, הוא מעולה!
  export const translations = {
    he: {
      dir: "rtl",
      // Nav
      navHome: "דף הבית",
      navSearch: "מצא מטפל",
      navQuiz: "שאלון התאמה",
      articles: "מאמרים",
      navJoin: "הצטרף כמטפל",
      navArticles: "מאמרים",
      navHowItWorks: "איך זה עובד?",
      navFaq: "שאלות נפוצות",
      navContact: "צור קשר",
      langLabel: "שפה",
      // Hero Search
      searchByName: "חיפוש לפי שם מטפל...",
      searchTitle: "מצא את המטפל המתאים לך",
      searchSubtitle: "פלטפורמה בטוחה ואמינה לחיבור עם פסיכולוגים, פסיכיאטרים ומטפלים מוסמכים בישראל.",
      searchBtn: "חיפוש",
      free: "✅ השירות חינמי לחלוטין למטופלים",
      therapistType: "סוג מטפל",
      city: "עיר",
      treatment: "תחום טיפול",
      treatmentMethod: "שיטת טיפול",
      hmo: "קופת חולים",
      format: "פורמט טיפול",
      language: "שפת טיפול",
      specializations: "תחומי טיפול",
      treatmentMethods: "שיטות טיפול",
      filterBy: "סינון לפי",
      all: "הכל",
      advancedFilters: "פילטרים מתקדמים",
      hideFilters: "הסתר פילטרים",
      selected: "נבחרו",
      gender: "מגדר",
      immediateAvailability: "זמינות מיידית",
      immediateOnly: "זמינים עכשיו",
      searchPlaceholder: "חפש לפי שם מטפל...",
      // Search page
      searchPageTitle: "חיפוש מטפלים",
      searchPageSubtitle: "מצא מטפל מוסמך ומאומת בקרבתך",
      noResults: "לא נמצאו מטפלים התואמים לסינון שלך",
      noResultsHint: "נסה לשנות את הפילטרים",
      filters: "פילטרים",
      sortBy: "מיין לפי",
      showing: "מציג",
      therapists: "מטפלים",
      // Therapist card labels
      verified: "מאומת",
      perSession: "לפגישה",
      yearsExp: "שנות ניסיון",
      viewProfile: "לפרופיל",
      availableNow: "זמין/ה עכשיו",
      notAvailable: "לא זמין/ה",
      // Quiz
      quizTitle: "שאלון התאמה אישית",
      quizSubtitle: "שאלות קצרות • ~2 דקות",
      quizBack: "חזרה",
      quizNext: "המשך",
      quizSkip: "דלג",
      quizLoading: "מנתח את תשובותיך...",
      quizLoadingSubtitle: "מוצא לך את המטפלים המתאימים ביותר מבין מאות מטפלים",
      quizResults: "המטפלים המומלצים עבורך",
      quizResultsSubtitle: "על פי תשובותיך, מצאנו את המטפלים המתאימים ביותר עבורך.",
      quizFreeService: "✅ השירות חינמי לחלוטין למטופלים",
      quizInfoDisclaimer: "ℹ️ אלו המלצות לחיבור בלבד – לא ייעוץ רפואי",
      quizBestMatch: "התאמה מיטבית",
      quizRestart: "התחל שאלון מחדש",
      quizViewAll: "צפה בכל המטפלים",
      quizProgress: "שאלה {current} מתוך {total}",
      // FAQ
      faqTitle: "שאלות נפוצות",
      faqSubtitle: "כל מה שרצית לדעת על מצא לי מטפל",
      faqAllCategories: "הכל",
      faqNotFound: "לא מצאת תשובה?",
      faqNotFoundSub: "נשמח לענות על כל שאלה בתוך 48 שעות",
      faqContact: "צור קשר",
      // How it Works
      howTitle: "איך זה עובד?",
      howSubtitle: "מצא לי מטפל מחברת בין מטופלים לאנשי מקצוע מוסמכים בתהליך פשוט, שקוף וחינמי לחלוטין.",
      howBadge: "פשוט, מהיר, חינמי",
      howFreeTitle: "100% חינמי למטופלים",
      howFreeDesc: "הפלטפורמה מממנת את עצמה דרך עמלה שגובה ממטפלים. המטופל אינו משלם דבר – לא עמלה, לא דמי מנוי, לא כלום. החיפוש, ההתאמה, ויצירת הקשר – הכל בחינם.",
      howFaqTitle: "שאלות נפוצות",
      howCta: "מצא מטפל עכשיו – חינם",
      howCtaQuiz: "שאלון התאמה חכם",
      // Articles
      articlesTitle: "ידע בריאות הנפש",
      articlesSubtitle: "מאמרים מקצועיים מאת מטפלים מוסמכים ומאומתים – לעזור לך להבין ולצמוח",
      articlesBadge: "ספריית מאמרים מקצועיים",
      articlesSearch: "חפש מאמרים...",
      articlesAll: "הכל",
      articlesFeatured: "מאמר מומלץ",
      articlesAll2: "כל המאמרים",
      articlesReadMore: "קרא/י עוד",
      articlesReadTime: "דקות קריאה",
      articlesNoResults: "לא נמצאו מאמרים התואמים לחיפוש",
      articlesSoon: "בקרוב יתפרסמו כאן מאמרים מקצועיים",
      articlesJoin: "הצטרף/י לפלטפורמה",
      articlesJoinText: "אתה/את מטפל/ת?",
      articlesPremium: "פרמיום",
      // Article detail
      articleBackBtn: "חזרה לכל המאמרים",
      articleDisclaimer: "מאמר זה נכתב לצרכי מידע בלבד ואינו מהווה ייעוץ רפואי, פסיכולוגי, או טיפולי. לכל שאלה מקצועית, פנה/י למטפל מוסמך.",
      articleCta: "מחפש/ת עזרה מקצועית?",
      articleCtaDesc: "מצא/י מטפל מוסמך ומאומת בקרבתך",
      articleCtaBtn: "חפש/י מטפל",
      articleCtaQuiz: "שאלון התאמה",
      articleVerified: "מאומת",
      // Register Therapist
      registerTitle: "הרשמה כמטפל",
      registerSubtitle: "הצטרפו לרשת המטפלים המקצועיים של מצא לי מטפל",
      registerSubmit: "שלח בקשת הצטרפות",
      registerSuccess: "הבקשה נשלחה בהצלחה!",
      registerSuccessDesc: "נבדוק את פרטיך ונחזור אליך בתוך 2-3 ימי עסקים.",
      // Contact Page
      contactTitle: "צור קשר",
      contactSubtitle: "יש לך שאלה? נשמח לעזור.",
      contactEmail: "אימייל",
      contactPhone: "טלפון",
      contactWhatsApp: "WhatsApp",
      contactHours: "ימים א׳–ה׳, 9:00–17:00",
      contactEmergency: "🆘 מצוקה נפשית דחופה?",
      contactEmergencyText: "במצבי משבר, פנה/י ל:",
      contactEmergencyBtn: "📞 1201 – קו חירום נפשי",
      contactFullName: "שם מלא",
      contactEmailLabel: "אימייל",
      contactSubjectLabel: "נושא",
      contactSubjectPlaceholder: "במה נוכל לעזור?",
      contactMessageLabel: "הודעה",
      contactMessagePlaceholder: "כתוב/י כאן את פנייתך...",
      contactSendBtn: "שלח הודעה",
      contactSent: "ההודעה נשלחה!",
      contactSentDesc: "נחזור אליך בהקדם.",
      contactSendAnother: "שלח הודעה נוספת",
      // Privacy
      privacyTitle: "מדיניות פרטיות",
      privacyLastUpdate: "עדכון אחרון: מרץ 2026",
      // Terms
      termsTitle: "תנאי שימוש",
      termsLastUpdate: "עדכון אחרון: מרץ 2026",
      termsEmergencyBtn: "📞 1201 – קו חירום נפשי",
      // Support Declaration
      supportTitle: "הצהרת תמיכה בגולשים",
      supportSubtitle: "אנחנו מתחייבים לספק לך חוויה בטוחה, מכבדת ואמינה. הנה ההתחייבויות שלנו אליך.",
      supportEmergencyTitle: "במצב חירום נפשי?",
      supportEmergencyDesc: "אם אתה/את או מישהו שאתה/את מכיר/ה נמצאים במשבר נפשי חריף – אל תהסס/י לפנות מיד:",
      supportEmergencyBtn: "1201 – עזרה נפשית ראשונה",
      supportContact: "לשאלות ופניות:",
      supportContactLink: "צור קשר",
      // Accessibility Statement
      accessibilityTitle: "הצהרת נגישות",
      accessibilityLastUpdate: "עדכון אחרון: מרץ 2026",
      // Footer
      footerDesc: "פלטפורמה בטוחה ומאומתת לחיבור עם אנשי מקצוע בתחום בריאות הנפש בישראל.",
      footerVerified: "כל המטפלים עוברים אימות רישיון לפני פרסום הפרופיל.",
      footerForPatients: "למטופלים",
      footerForTherapists: "למטפלים",
      footerLegal: "מידע משפטי",
      footerCopyright: "© 2026 מצא לי מטפל. כל הזכויות שמורות.",
      footerDisclaimer: "הפלטפורמה אינה מספקת ייעוץ רפואי. לעזרה דחופה התקשר/י ל-1201.",
      footerEmergency: "עזרה נפשית ראשונה – 1201",
      // Stats
      statsVerified: "מטפלים מאומתים",
      statsSatisfaction: "שביעות רצון",
      statsConnected: "מטופלים חוברו",
      statsHoursSuffix: " שעות",
      statsWait: "ממוצע המתנה לפגישה ראשונה",
      // How It Works steps
      howStepsSubtitle: "שלושה שלבים פשוטים לקביעת פגישה ראשונה עם המטפל שלך",
      howStep1Title: "חפש/י מטפל",
      howStep1Desc: "השתמש/י בחיפוש המתקדם כדי לסנן לפי מיקום, התמחות, מחיר ועוד.",
      howStep2Title: "קבל/י המלצות AI",
      howStep2Desc: "מלא/י את שאלון ההתאמה הקצר וקבל/י 5 מטפלים שנבחרו במיוחד עבורך.",
      howStep3Title: "פנה/י למטפל",
      howStep3Desc: "שלח/י הודעה ישירות למטפל שבחרת ותאם/י פגישת היכרות.",
      // Why Choose Us
      whyTitle: "למה מצא לי מטפל?",
      whySubtitle: "הדרך הבטוחה למצוא את המטפל שמתאים בדיוק לך",
      whyVerifiedTitle: "מטפלים מאומתים",
      whyVerifiedDesc: "כל המטפלים בפלטפורמה עוברים תהליך אימות רישיון ומקצועיות.",
      whySmartTitle: "התאמה חכמה",
      whySmartDesc: "שאלון AI מתקדם שמוצא את המטפל המתאים ביותר לצרכים שלך.",
      whyPrivacyTitle: "פרטיות מלאה",
      whyPrivacyDesc: "החיפוש שלך פרטי ומאובטח. אנחנו לא שומרים מידע רפואי.",
      whyTransparentTitle: "שקיפות מלאה",
      whyTransparentDesc: "מחירים ברורים, ביקורות אמיתיות וכל המידע לפני שתפנו.",
      // Testimonials
      testimonialsTitle: "מה אומרים המשתמשים שלנו",
      testimonialsSubtitle: "חוויות אמיתיות מאנשים שמצאו עזרה דרכנו",
      testimonialsDisclaimer: "* שמות משתמשים ופרטים מוצגים בקיצור לשמירה על פרטיות",
      // Quiz CTA
      quizCtaTitle: "לא יודעים מאיפה להתחיל?",
      quizCtaDesc: "שאלון ההתאמה שלנו יעזור לכם למצוא את המטפל המתאים בדיוק בתוך 2 דקות.",
      quizCtaBtn: "התחל בשאלון",
      // For Therapists CTA
      forTherapistsTitle: "הצטרף/י לרשת המטפלים שלנו",
      forTherapistsDesc: "הגע/י למטופלים חדשים ובנה/י נוכחות דיגיטלית מקצועית. הצטרפות חינמית — אנו מאמתים ומקדמים את הפרופיל שלך.",
      forTherapistsPerk1: "תג אימות רישיון מקצועי",
      forTherapistsPerk2: "גישה לאלפי מטופלים פוטנציאליים",
      forTherapistsPerk3: "ניהול פרופיל ועמוד אישי",
      // Featured
      featuredTitle: "מטפלים מובילים",
      featuredSubtitle: "מאומתים, מדורגים ומומלצים",
      featuredViewAll: "צפה בכולם",
      // Articles Section (homepage)
      articlesSectionTitle: "מאמרים מקצועיים",
      articlesSectionSubtitle: "ידע ותובנות מאת מטפלים מוסמכים",
      articlesSectionViewAll: "לכל המאמרים",
      // Tips
      tipsTitle: "טיפים לבריאות הנפש",
      tipsSubtitle: "ידע מעשי שאפשר ליישם כבר היום",
      tipCbtTitle: "CBT – שינוי דפוסי חשיבה",
      tipCbtDesc: "טיפול קוגניטיבי-התנהגותי מוכח מחקרית לחרדה ודיכאון. עובד על זיהוי ושינוי מחשבות אוטומטיות שליליות.",
      tipWhenTitle: "מתי לפנות לעזרה?",
      tipWhenDesc: "אם תחושות של עצב, חרדה, או לחץ נמשכות מעל שבועיים ומשפיעות על חיי היומיום – זה הזמן הנכון לפנות.",
      tipBreathTitle: "נשימה עמוקה לחרדה",
      tipBreathDesc: "שאפי 4 שניות, החזיקי 4 שניות, נשפי 6 שניות. טכניקה זו מפעילה את מערכת העצבים הפאראסימפטטית ומרגיעה.",
      tipMorningTitle: "שגרת בוקר בריאה",
      tipMorningDesc: "שגרת בוקר קבועה – שינה מספקת, פעילות גופנית קלה, וארוחת בוקר – משפרת מצב רוח ומפחיתה חרדה.",
      tipSleepTitle: "היגיינת שינה",
      tipSleepDesc: "מסכים כחצי שעה לפני שינה, שעת שינה קבועה, וחדר קריר ואפל – שלוש ההמלצות הבסיסיות לשינה טובה.",
      tipMindTitle: "מיינדפולנס – 5 דקות ביום",
      tipMindDesc: "5 דקות של נוכחות מודעת ביום – מיקוד בנשימה, בתחושות הגוף – מפחיתות לחץ ומגבירות ריכוז לאורך זמן.",
      // Filter panel
      filterReset: "איפוס",
      filterProfession: "מקצוע",
      filterAllCities: "כל הערים",
      filterMaxBudget: "תקציב מקסימלי",
      // Professions
      profPsychologist: "פסיכולוג/ית",
      profPsychiatrist: "פסיכיאטר/ית",
      profPsychotherapist: "פסיכותרפיסט/ית",
      profSocialWorker: "עו\"ס קליני",
      profCounselor: "יועץ/ת",
      // Formats
      formatInPerson: "פנים אל פנים",
      formatZoom: "זום",
      formatPhone: "טלפון",
      // HMOs
      hmoMaccabi: "מכבי",
      hmoClalit: "כללית",
      hmoMeuhedet: "מאוחדת",
      hmoLeumit: "לאומית",
      hmoMenora: "מנורה מבטחים",
      hmoHarel: "הראל",
      hmoClal: "כלל ביטוח",
      hmoMigdal: "מגדל",
      hmoPhoenix: "הפניקס",
      hmoAyalon: "איילון",
      hmoPrivate: "פרטי (ללא ביטוח)",
      // Languages
      langHebrew: "עברית",
      langEnglish: "אנגלית",
      langArabic: "ערבית",
      langRussian: "רוסית",
      langFrench: "צרפתית",
      langSpanish: "ספרדית",
      langAmharic: "אמהרית",
      // Gender
      genderFemale: "נשית",
      genderMale: "גברית",
      // Register Therapist form
      registerPhotoAlt: "תמונת פרופיל",
      registerPhotoLabel: "תמונת פרופיל",
      registerPhotoHint: "תמונה מקצועית מגדילה את אמון המטופלים",
      registerUploadPhoto: "העלה תמונה",
      registerUploading: "מעלה...",
      registerPhotoUploaded: "תמונה הועלתה בהצלחה",
      registerLicenseUploaded: "מסמך הועלה בהצלחה ✓",
      registerFullName: "שם מלא",
      registerFullNamePlaceholder: "ד״ר ישראל לוי",
      registerLicenseNumber: "מספר רישיון",
      registerProfession: "מקצוע",
      registerSelectProfession: "בחר מקצוע",
      registerAbout: "אודות",
      registerAboutPlaceholder: "ספר/י על גישת הטיפול שלך, ניסיונך והתמחויותיך...",
      registerCity: "עיר",
      registerCityPlaceholder: "תל אביב",
      registerPrice: "מחיר לפגישה (₪)",
      registerPhone: "טלפון",
      registerEmail: "אימייל",
      registerFormat: "פורמט טיפול",
      registerHmo: "קופות חולים וחברות ביטוח",
      registerTreatmentMethods: "שיטות טיפול",
      registerSpecializations: "תחומי טיפול והתמחויות",
      registerLanguages: "שפות טיפול",
      registerLicenseDoc: "העלאת מסמך רישיון מקצועי (מומלץ)",
      registerLicenseDocHint: "העלה/י תעודת הסמכה, רישיון מקצועי, או אישור מהרשות המוסמכת.",
      registerReplaceFile: "החלף קובץ",
      registerChooseFile: "בחר קובץ (PDF / תמונה)",
      registerFootnote: "הפרופיל יפורסם רק לאחר אימות הרישיון המקצועי",
      registerRequiredFields: "יש למלא שדות חובה",
      // Accessibility Menu
      a11yMenuTitle: "נגישות – WCAG 2.1 AAA",
      a11yClose: "סגור תפריט נגישות",
      a11yQuickProfiles: "פרופילים מהירים",
      a11ySeizureSafe: "בטוח לאפילפסיה",
      a11yVisionImpaired: "לקוי ראייה",
      a11yCognitive: "קוגניטיבי",
      a11yAdhd: "ADHD ידידותי",
      a11yKeyboard: "ניווט מקלדת",
      a11yReset: "איפוס",
      a11yFontSize: "גודל טקסט",
      a11yDecrease: "הקטן",
      a11yIncrease: "הגדל",
      a11yDecreaseLabel: "הקטן טקסט",
      a11yIncreaseLabel: "הגדל טקסט",
      a11yDisplay: "תצוגה",
      a11yHighContrast: "ניגודיות גבוהה",
      a11yInvertColors: "היפוך צבעים",
      a11yGrayscale: "גווני אפור",
      a11ySeizureSafeMode: "מצב בטוח לאפילפסיה",
      a11yReading: "קריאה",
      a11yReadableFont: "פונט קריא (Arial)",
      a11yLineSpacing: "ריווח שורות מוגבר",
      a11yHighlightLinks: "הדגש קישורים",
      a11yNavMotor: "ניווט ומנוע",
      a11yLargeCursor: "סמן עכבר גדול",
      a11yFocusHighlight: "הדגשת מיקוד (Focus)",
      a11yStopAnimations: "עצור אנימציות",
      a11yAdhdFriendly: "מצב ADHD ידידותי",
      a11yResetAll: "אפס את כל ההגדרות",
      a11yWcag: "תואם WCAG 2.1/2.2 AAA",
      a11yOn: "פעיל",
      a11yOff: "כבוי",
      a11yAriaLabel: "תפריט נגישות",
      a11yAriaDialog: "אפשרויות נגישות",
    },

    en: {
      lang: "en",
      dir: "ltr",
      // Nav
      navHome: "Home",
      articles: "Articles",
      navSearch: "Find Therapists",
      navQuiz: "Match Me",
      navJoin: "Join as Therapist",
      navArticles: "Articles",
      navHowItWorks: "How It Works",
      navFaq: "FAQ",
      navContact: "Contact",
      langLabel: "Language",
      // Hero Search
      searchByName: "Search by therapist name...",
      searchTitle: "Find Your Perfect Therapist",
      searchSubtitle: "A safe and trusted platform connecting you with certified psychologists, psychiatrists and therapists in Israel.",
      searchBtn: "Search",
      free: "✅ Completely free for patients",
      therapistType: "Therapist Type",
      city: "City",
      treatment: "Specialization",
      treatmentMethod: "Treatment Method",
      hmo: "Health Fund",
      format: "Session Format",
      language: "Treatment Language",
      specializations: "Specializations",
      treatmentMethods: "Treatment Methods",
      filterBy: "Filter by",
      all: "All",
      advancedFilters: "Advanced Filters",
      hideFilters: "Hide Filters",
      selected: "selected",
      gender: "Gender",
      immediateAvailability: "Immediate Availability",
      immediateOnly: "Available Now",
      searchPlaceholder: "Search by therapist name...",
      // Search page
      searchPageTitle: "Find a Therapist",
      searchPageSubtitle: "Find a certified and verified therapist near you",
      noResults: "No therapists match your filters",
      noResultsHint: "Try adjusting your filters",
      filters: "Filters",
      sortBy: "Sort by",
      showing: "Showing",
      therapists: "therapists",
      // Therapist card labels
      verified: "Verified",
      perSession: "per session",
      yearsExp: "years experience",
      viewProfile: "View Profile",
      availableNow: "Available Now",
      notAvailable: "Not Available",
      // Quiz
      quizTitle: "Personal Matching Quiz",
      quizSubtitle: "Short questions • ~2 minutes",
      quizBack: "Back",
      quizNext: "Continue",
      quizSkip: "Skip",
      quizLoading: "Analyzing your answers...",
      quizLoadingSubtitle: "Finding the best therapists for you from hundreds of professionals",
      quizResults: "Your Recommended Therapists",
      quizResultsSubtitle: "Based on your answers, we found the most suitable therapists for you.",
      quizFreeService: "✅ Completely free for patients",
      quizInfoDisclaimer: "ℹ️ These are referral recommendations only – not medical advice",
      quizBestMatch: "Best Match",
      quizRestart: "Restart Quiz",
      quizViewAll: "View All Therapists",
      quizProgress: "Question {current} of {total}",
      // FAQ
      faqTitle: "Frequently Asked Questions",
      faqSubtitle: "Everything you wanted to know about Find My Therapist",
      faqAllCategories: "All",
      faqNotFound: "Didn't find an answer?",
      faqNotFoundSub: "We'll be happy to answer within 48 hours",
      faqContact: "Contact Us",
      // How it Works
      howTitle: "How It Works",
      howSubtitle: "Find My Therapist connects patients with certified professionals in a simple, transparent, and completely free process.",
      howBadge: "Simple, Fast, Free",
      howFreeTitle: "100% Free for Patients",
      howFreeDesc: "The platform is funded through fees charged to therapists. Patients pay nothing – no commission, no subscription, nothing. Search, match, and contact – all free.",
      howFaqTitle: "Frequently Asked Questions",
      howCta: "Find a Therapist Now – Free",
      howCtaQuiz: "Smart Matching Quiz",
      // Articles
      articlesTitle: "Mental Health Knowledge",
      articlesSubtitle: "Professional articles by certified and verified therapists – to help you understand and grow",
      articlesBadge: "Professional Article Library",
      articlesSearch: "Search articles...",
      articlesAll: "All",
      articlesFeatured: "Featured Article",
      articlesAll2: "All Articles",
      articlesReadMore: "Read more",
      articlesReadTime: "min read",
      articlesNoResults: "No articles match your search",
      articlesSoon: "Professional articles will be published here soon",
      articlesJoin: "Join the platform",
      articlesJoinText: "Are you a therapist?",
      articlesPremium: "Premium",
      // Article detail
      articleBackBtn: "Back to all articles",
      articleDisclaimer: "This article is written for informational purposes only and does not constitute medical, psychological, or therapeutic advice. For professional questions, consult a licensed therapist.",
      articleCta: "Looking for Professional Help?",
      articleCtaDesc: "Find a certified and verified therapist near you",
      articleCtaBtn: "Find a Therapist",
      articleCtaQuiz: "Matching Quiz",
      articleVerified: "Verified",
      // Register Therapist
      registerTitle: "Register as a Therapist",
      registerSubtitle: "Join the professional therapist network of Find My Therapist",
      registerSubmit: "Submit Registration Request",
      registerSuccess: "Request sent successfully!",
      registerSuccessDesc: "We will review your details and get back to you within 2-3 business days.",
      // Contact Page
      contactTitle: "Contact Us",
      contactSubtitle: "Have a question? We'd love to help.",
      contactEmail: "Email",
      contactPhone: "Phone",
      contactWhatsApp: "WhatsApp",
      contactHours: "Sun–Thu, 9:00–17:00",
      contactEmergency: "🆘 Mental Health Emergency?",
      contactEmergencyText: "In crisis situations, contact:",
      contactEmergencyBtn: "📞 1201 – Mental Health Hotline",
      contactFullName: "Full Name",
      contactEmailLabel: "Email",
      contactSubjectLabel: "Subject",
      contactSubjectPlaceholder: "How can we help?",
      contactMessageLabel: "Message",
      contactMessagePlaceholder: "Write your message here...",
      contactSendBtn: "Send Message",
      contactSent: "Message Sent!",
      contactSentDesc: "We'll get back to you shortly.",
      contactSendAnother: "Send Another Message",
      // Privacy
      privacyTitle: "Privacy Policy",
      privacyLastUpdate: "Last updated: March 2026",
      // Terms
      termsTitle: "Terms of Use",
      termsLastUpdate: "Last updated: March 2026",
      termsEmergencyBtn: "📞 1201 – Mental Health Hotline",
      // Support Declaration
      supportTitle: "User Support Declaration",
      supportSubtitle: "We are committed to providing you with a safe, respectful and trustworthy experience. Here are our commitments to you.",
      supportEmergencyTitle: "Mental Health Emergency?",
      supportEmergencyDesc: "If you or someone you know is in an acute mental health crisis – don't hesitate to reach out immediately:",
      supportEmergencyBtn: "1201 – Mental Health First Aid",
      supportContact: "Questions and inquiries:",
      supportContactLink: "Contact Us",
      // Accessibility Statement
      accessibilityTitle: "Accessibility Statement",
      accessibilityLastUpdate: "Last updated: March 2026",
      // Footer
      footerDesc: "A safe and verified platform connecting with mental health professionals in Israel.",
      footerVerified: "All therapists undergo license verification before their profile is published.",
      footerForPatients: "For Patients",
      footerForTherapists: "For Therapists",
      footerLegal: "Legal",
      footerCopyright: "© 2026 Find My Therapist. All rights reserved.",
      footerDisclaimer: "This platform does not provide medical advice. For urgent help call 1201.",
      footerEmergency: "Mental Health First Aid – 1201",
      // Stats
      statsVerified: "Verified Therapists",
      statsSatisfaction: "Satisfaction",
      statsConnected: "Patients Connected",
      statsHoursSuffix: " hours",
      statsWait: "Avg. wait for first session",
      // How It Works steps
      howStepsSubtitle: "Three simple steps to schedule your first session",
      howStep1Title: "Search for a Therapist",
      howStep1Desc: "Use the advanced search to filter by location, specialization, price and more.",
      howStep2Title: "Get AI Recommendations",
      howStep2Desc: "Complete the short matching quiz and receive 5 therapists chosen especially for you.",
      howStep3Title: "Contact the Therapist",
      howStep3Desc: "Send a message directly to your chosen therapist and schedule a first meeting.",
      // Why Choose Us
      whyTitle: "Why Find My Therapist?",
      whySubtitle: "The safe way to find the therapist that fits you perfectly",
      whyVerifiedTitle: "Verified Therapists",
      whyVerifiedDesc: "All therapists on the platform undergo license and professional verification.",
      whySmartTitle: "Smart Matching",
      whySmartDesc: "Advanced AI quiz that finds the most suitable therapist for your needs.",
      whyPrivacyTitle: "Full Privacy",
      whyPrivacyDesc: "Your search is private and secure. We do not store medical information.",
      whyTransparentTitle: "Full Transparency",
      whyTransparentDesc: "Clear prices, real reviews and all information before you contact.",
      // Testimonials
      testimonialsTitle: "What Our Users Say",
      testimonialsSubtitle: "Real experiences from people who found help through us",
      testimonialsDisclaimer: "* Usernames and details are abbreviated to protect privacy",
      // Quiz CTA
      quizCtaTitle: "Don't know where to start?",
      quizCtaDesc: "Our matching quiz will help you find the perfect therapist in just 2 minutes.",
      quizCtaBtn: "Start the Quiz",
      // For Therapists CTA
      forTherapistsTitle: "Join Our Therapist Network",
      forTherapistsDesc: "Reach new patients and build a professional digital presence. Free to join — we verify and promote your profile.",
      forTherapistsPerk1: "Professional license verification badge",
      forTherapistsPerk2: "Access to thousands of potential patients",
      forTherapistsPerk3: "Profile and personal page management",
      // Featured
      featuredTitle: "Top Therapists",
      featuredSubtitle: "Verified, rated and recommended",
      featuredViewAll: "View All",
      // Articles Section (homepage)
      articlesSectionTitle: "Professional Articles",
      articlesSectionSubtitle: "Knowledge and insights from certified therapists",
      articlesSectionViewAll: "All Articles",
      // Tips
      tipsTitle: "Mental Health Tips",
      tipsSubtitle: "Practical knowledge you can apply today",
      tipCbtTitle: "CBT – Changing Thought Patterns",
      tipCbtDesc: "Research-proven cognitive behavioral therapy for anxiety and depression. Works by identifying and changing negative automatic thoughts.",
      tipWhenTitle: "When to Seek Help?",
      tipWhenDesc: "If feelings of sadness, anxiety, or stress last more than two weeks and affect daily life – it's the right time to reach out.",
      tipBreathTitle: "Deep Breathing for Anxiety",
      tipBreathDesc: "Inhale 4 seconds, hold 4 seconds, exhale 6 seconds. This technique activates the parasympathetic nervous system and calms you.",
      tipMorningTitle: "Healthy Morning Routine",
      tipMorningDesc: "A consistent morning routine – adequate sleep, light exercise, and breakfast – improves mood and reduces anxiety.",
      tipSleepTitle: "Sleep Hygiene",
      tipSleepDesc: "Screens off half an hour before bed, consistent bedtime, and a cool dark room – the three basic recommendations for good sleep.",
      tipMindTitle: "Mindfulness – 5 Minutes a Day",
      tipMindDesc: "5 minutes of mindful presence a day – focusing on breathing and body sensations – reduces stress and improves concentration.",
      // Filter panel
      filterReset: "Reset",
      filterProfession: "Profession",
      filterAllCities: "All Cities",
      filterMaxBudget: "Max Budget",
      // Professions
      profPsychologist: "Psychologist",
      profPsychiatrist: "Psychiatrist",
      profPsychotherapist: "Psychotherapist",
      profSocialWorker: "Clinical Social Worker",
      profCounselor: "Counselor",
      // Formats
      formatInPerson: "In Person",
      formatZoom: "Zoom",
      formatPhone: "Phone",
      // HMOs
      hmoMaccabi: "Maccabi",
      hmoClalit: "Clalit",
      hmoMeuhedet: "Meuhedet",
      hmoLeumit: "Leumit",
      hmoMenora: "Menora Mivtachim",
      hmoHarel: "Harel",
      hmoClal: "Clal Insurance",
      hmoMigdal: "Migdal",
      hmoPhoenix: "Phoenix",
      hmoAyalon: "Ayalon",
      hmoPrivate: "Private (No Insurance)",
      // Languages
      langHebrew: "Hebrew",
      langEnglish: "English",
      langArabic: "Arabic",
      langRussian: "Russian",
      langFrench: "French",
      langSpanish: "Spanish",
      langAmharic: "Amharic",
      // Gender
      genderFemale: "Female",
      genderMale: "Male",
      // Register Therapist form
      registerPhotoAlt: "Profile photo",
      registerPhotoLabel: "Profile Photo",
      registerPhotoHint: "A professional photo increases patient trust",
      registerUploadPhoto: "Upload Photo",
      registerUploading: "Uploading...",
      registerPhotoUploaded: "Photo uploaded successfully",
      registerLicenseUploaded: "Document uploaded successfully ✓",
      registerFullName: "Full Name",
      registerFullNamePlaceholder: "Dr. John Smith",
      registerLicenseNumber: "License Number",
      registerProfession: "Profession",
      registerSelectProfession: "Select profession",
      registerAbout: "About",
      registerAboutPlaceholder: "Tell us about your therapy approach, experience and specializations...",
      registerCity: "City",
      registerCityPlaceholder: "Tel Aviv",
      registerPrice: "Price per Session (₪)",
      registerPhone: "Phone",
      registerEmail: "Email",
      registerFormat: "Treatment Format",
      registerHmo: "Health Funds & Insurance Companies",
      registerTreatmentMethods: "Treatment Methods",
      registerSpecializations: "Treatment Areas & Specializations",
      registerLanguages: "Treatment Languages",
      registerLicenseDoc: "Upload Professional License Document (Recommended)",
      registerLicenseDocHint: "Upload a certification, professional license, or approval from the competent authority.",
      registerReplaceFile: "Replace File",
      registerChooseFile: "Choose File (PDF / Image)",
      registerFootnote: "Profile will only be published after license verification",
      registerRequiredFields: "Please fill in required fields",
      // Accessibility Menu
      a11yMenuTitle: "Accessibility – WCAG 2.1 AAA",
      a11yClose: "Close accessibility menu",
      a11yQuickProfiles: "Quick Profiles",
      a11ySeizureSafe: "Seizure Safe",
      a11yVisionImpaired: "Vision Impaired",
      a11yCognitive: "Cognitive",
      a11yAdhd: "ADHD Friendly",
      a11yKeyboard: "Keyboard Nav",
      a11yReset: "Reset",
      a11yFontSize: "Text Size",
      a11yDecrease: "Decrease",
      a11yIncrease: "Increase",
      a11yDecreaseLabel: "Decrease text size",
      a11yIncreaseLabel: "Increase text size",
      a11yDisplay: "Display",
      a11yHighContrast: "High Contrast",
      a11yInvertColors: "Invert Colors",
      a11yGrayscale: "Grayscale",
      a11ySeizureSafeMode: "Seizure Safe Mode",
      a11yReading: "Reading",
      a11yReadableFont: "Readable Font (Arial)",
      a11yLineSpacing: "Increased Line Spacing",
      a11yHighlightLinks: "Highlight Links",
      a11yNavMotor: "Navigation & Motor",
      a11yLargeCursor: "Large Cursor",
      a11yFocusHighlight: "Focus Highlight",
      a11yStopAnimations: "Stop Animations",
      a11yAdhdFriendly: "ADHD Friendly Mode",
      a11yResetAll: "Reset All Settings",
      a11yWcag: "Compliant with WCAG 2.1/2.2 AAA",
      a11yOn: "On",
      a11yOff: "Off",
      a11yAriaLabel: "Accessibility menu",
      a11yAriaDialog: "Accessibility options",
    },

    ru: {
      lang: "ru",
      dir: "ltr",
      // Nav
      navHome: "Главная",
      articles: "Статьи",
      navSearch: "Найти терапевта",
      navQuiz: "Подобрать терапевта",
      navJoin: "Зарегистрироваться",
      navArticles: "Статьи",
      navHowItWorks: "Как это работает",
      navFaq: "FAQ",
      navContact: "Контакты",
      langLabel: "Язык",
      // Hero Search
      searchByName: "Поиск по имени терапевта...",
      searchTitle: "Найдите своего терапевта",
      searchSubtitle: "Безопасная и надёжная платформа для связи с психологами, психиатрами и терапевтами в Израиле.",
      searchBtn: "Поиск",
      free: "✅ Полностью бесплатно для пациентов",
      therapistType: "Тип терапевта",
      city: "Город",
      treatment: "Специализация",
      treatmentMethod: "Метод терапии",
      hmo: "Больничная касса",
      format: "Формат сеанса",
      language: "Язык терапии",
      specializations: "Специализации",
      treatmentMethods: "Методы лечения",
      filterBy: "Фильтр по",
      all: "Все",
      advancedFilters: "Расширенные фильтры",
      hideFilters: "Скрыть фильтры",
      selected: "выбрано",
      gender: "Пол",
      immediateAvailability: "Немедленная доступность",
      immediateOnly: "Доступны сейчас",
      searchPlaceholder: "Поиск по имени терапевта...",
      // Search page
      searchPageTitle: "Найти терапевта",
      searchPageSubtitle: "Найдите сертифицированного и проверенного терапевта рядом с вами",
      noResults: "Терапевты не найдены по вашим фильтрам",
      noResultsHint: "Попробуйте изменить фильтры",
      filters: "Фильтры",
      sortBy: "Сортировать по",
      showing: "Показано",
      therapists: "терапевтов",
      // Therapist card labels
      verified: "Проверен",
      perSession: "за сеанс",
      yearsExp: "лет опыта",
      viewProfile: "Профиль",
      availableNow: "Доступен/на сейчас",
      notAvailable: "Недоступен/на",
      // Quiz
      quizTitle: "Персональный тест подбора",
      quizSubtitle: "Короткие вопросы • ~2 минуты",
      quizBack: "Назад",
      quizNext: "Продолжить",
      quizSkip: "Пропустить",
      quizLoading: "Анализируем ваши ответы...",
      quizLoadingSubtitle: "Подбираем лучших терапевтов из сотен специалистов",
      quizResults: "Рекомендованные терапевты",
      quizResultsSubtitle: "На основе ваших ответов мы нашли наиболее подходящих терапевтов.",
      quizFreeService: "✅ Полностью бесплатно для пациентов",
      quizInfoDisclaimer: "ℹ️ Только рекомендации – не медицинский совет",
      quizBestMatch: "Лучшее совпадение",
      quizRestart: "Пройти тест заново",
      quizViewAll: "Все терапевты",
      quizProgress: "Вопрос {current} из {total}",
      // FAQ
      faqTitle: "Часто задаваемые вопросы",
      faqSubtitle: "Всё что вы хотели знать о Find My Therapist",
      faqAllCategories: "Все",
      faqNotFound: "Не нашли ответ?",
      faqNotFoundSub: "Мы ответим на любой вопрос в течение 48 часов",
      faqContact: "Связаться с нами",
      // How it Works
      howTitle: "Как это работает?",
      howSubtitle: "Find My Therapist соединяет пациентов с сертифицированными специалистами в простом, прозрачном и полностью бесплатном процессе.",
      howBadge: "Просто, быстро, бесплатно",
      howFreeTitle: "100% бесплатно для пациентов",
      howFreeDesc: "Платформа финансируется за счёт комиссий от терапевтов. Пациенты ничего не платят – никаких комиссий, подписок, ничего. Поиск, подбор и контакт – всё бесплатно.",
      howFaqTitle: "Часто задаваемые вопросы",
      howCta: "Найти терапевта сейчас – бесплатно",
      howCtaQuiz: "Умный тест подбора",
      // Articles
      articlesTitle: "Знания о психическом здоровье",
      articlesSubtitle: "Профессиональные статьи от сертифицированных и проверенных терапевтов – чтобы помочь вам понять и развиваться",
      articlesBadge: "Библиотека профессиональных статей",
      articlesSearch: "Поиск статей...",
      articlesAll: "Все",
      articlesFeatured: "Рекомендуемая статья",
      articlesAll2: "Все статьи",
      articlesReadMore: "Читать далее",
      articlesReadTime: "мин чтения",
      articlesNoResults: "Статьи не найдены",
      articlesSoon: "Здесь скоро появятся профессиональные статьи",
      articlesJoin: "Присоединиться к платформе",
      articlesJoinText: "Вы терапевт?",
      articlesPremium: "Премиум",
      // Article detail
      articleBackBtn: "Назад ко всем статьям",
      articleDisclaimer: "Эта статья написана только в информационных целях и не является медицинским, психологическим или терапевтическим советом. По профессиональным вопросам обратитесь к лицензированному терапевту.",
      articleCta: "Ищете профессиональную помощь?",
      articleCtaDesc: "Найдите сертифицированного и проверенного терапевта рядом с вами",
      articleCtaBtn: "Найти терапевта",
      articleCtaQuiz: "Тест подбора",
      articleVerified: "Проверен",
      // Register Therapist
      registerTitle: "Регистрация как терапевт",
      registerSubtitle: "Присоединяйтесь к профессиональной сети терапевтов Find My Therapist",
      registerSubmit: "Отправить заявку на регистрацию",
      registerSuccess: "Заявка успешно отправлена!",
      registerSuccessDesc: "Мы проверим ваши данные и свяжемся с вами в течение 2-3 рабочих дней.",
      // Contact Page
      contactTitle: "Связаться с нами",
      contactSubtitle: "Есть вопрос? Мы рады помочь.",
      contactEmail: "Электронная почта",
      contactPhone: "Телефон",
      contactWhatsApp: "WhatsApp",
      contactHours: "Вс–Чт, 9:00–17:00",
      contactEmergency: "🆘 Психическая помощь срочно?",
      contactEmergencyText: "В кризисных ситуациях обратитесь:",
      contactEmergencyBtn: "📞 1201 – Линия экстренной психологической помощи",
      contactFullName: "Полное имя",
      contactEmailLabel: "Электронная почта",
      contactSubjectLabel: "Тема",
      contactSubjectPlaceholder: "Чем можем помочь?",
      contactMessageLabel: "Сообщение",
      contactMessagePlaceholder: "Напишите ваше сообщение здесь...",
      contactSendBtn: "Отправить сообщение",
      contactSent: "Сообщение отправлено!",
      contactSentDesc: "Мы свяжемся с вами в ближайшее время.",
      contactSendAnother: "Отправить ещё сообщение",
      // Privacy
      privacyTitle: "Политика конфиденциальности",
      privacyLastUpdate: "Последнее обновление: март 2026",
      // Terms
      termsTitle: "Условия использования",
      termsLastUpdate: "Последнее обновление: март 2026",
      termsEmergencyBtn: "📞 1201 – Линия экстренной психологической помощи",
      // Support Declaration
      supportTitle: "Декларация поддержки пользователей",
      supportSubtitle: "Мы обязуемся предоставить вам безопасный, уважительный и надёжный опыт. Вот наши обязательства перед вами.",
      supportEmergencyTitle: "Психическая помощь срочно?",
      supportEmergencyDesc: "Если вы или кто-то из ваших знакомых находится в остром психическом кризисе – не стесняйтесь обратиться немедленно:",
      supportEmergencyBtn: "1201 – Первая психологическая помощь",
      supportContact: "Вопросы и обращения:",
      supportContactLink: "Связаться с нами",
      // Accessibility Statement
      accessibilityTitle: "Декларация доступности",
      accessibilityLastUpdate: "Последнее обновление: март 2026",
      // Footer
      footerDesc: "Безопасная и проверенная платформа для связи со специалистами в области психического здоровья в Израиле.",
      footerVerified: "Все терапевты проходят проверку лицензии перед публикацией профиля.",
      footerForPatients: "Для пациентов",
      footerForTherapists: "Для терапевтов",
      footerLegal: "Правовая информация",
      footerCopyright: "© 2026 Find My Therapist. Все права защищены.",
      footerDisclaimer: "Платформа не предоставляет медицинских консультаций. Для срочной помощи звоните 1201.",
      footerEmergency: "Первая психологическая помощь – 1201",
      // Stats
      statsVerified: "Проверенных терапевтов",
      statsSatisfaction: "Удовлетворённость",
      statsConnected: "Пациентов подключено",
      statsHoursSuffix: " часов",
      statsWait: "Среднее ожидание первого сеанса",
      // How It Works steps
      howStepsSubtitle: "Три простых шага для записи на первый сеанс",
      howStep1Title: "Найдите терапевта",
      howStep1Desc: "Используйте расширенный поиск для фильтрации по местоположению, специализации, цене и др.",
      howStep2Title: "Получите рекомендации AI",
      howStep2Desc: "Пройдите короткий тест подбора и получите 5 терапевтов, выбранных специально для вас.",
      howStep3Title: "Свяжитесь с терапевтом",
      howStep3Desc: "Отправьте сообщение выбранному терапевту и запланируйте первую встречу.",
      // Why Choose Us
      whyTitle: "Почему Find My Therapist?",
      whySubtitle: "Безопасный способ найти терапевта, который подходит именно вам",
      whyVerifiedTitle: "Проверенные терапевты",
      whyVerifiedDesc: "Все терапевты платформы проходят проверку лицензии и профессионализма.",
      whySmartTitle: "Умный подбор",
      whySmartDesc: "Расширенный AI-тест, который находит наиболее подходящего терапевта для ваших нужд.",
      whyPrivacyTitle: "Полная конфиденциальность",
      whyPrivacyDesc: "Ваш поиск приватен и защищён. Мы не храним медицинскую информацию.",
      whyTransparentTitle: "Полная прозрачность",
      whyTransparentDesc: "Чёткие цены, реальные отзывы и вся информация до обращения.",
      // Testimonials
      testimonialsTitle: "Что говорят наши пользователи",
      testimonialsSubtitle: "Реальный опыт людей, нашедших помощь через нас",
      testimonialsDisclaimer: "* Имена пользователей сокращены для защиты конфиденциальности",
      // Quiz CTA
      quizCtaTitle: "Не знаете с чего начать?",
      quizCtaDesc: "Наш тест подбора поможет найти идеального терапевта всего за 2 минуты.",
      quizCtaBtn: "Начать тест",
      // For Therapists CTA
      forTherapistsTitle: "Присоединяйтесь к нашей сети терапевтов",
      forTherapistsDesc: "Находите новых пациентов и создавайте профессиональное цифровое присутствие. Регистрация бесплатна.",
      forTherapistsPerk1: "Значок проверки профессиональной лицензии",
      forTherapistsPerk2: "Доступ к тысячам потенциальных пациентов",
      forTherapistsPerk3: "Управление профилем и личной страницей",
      // Featured
      featuredTitle: "Ведущие терапевты",
      featuredSubtitle: "Проверенные, оценённые и рекомендованные",
      featuredViewAll: "Все терапевты",
      // Articles Section (homepage)
      articlesSectionTitle: "Профессиональные статьи",
      articlesSectionSubtitle: "Знания и идеи от сертифицированных терапевтов",
      articlesSectionViewAll: "Все статьи",
      // Tips
      tipsTitle: "Советы по психическому здоровью",
      tipsSubtitle: "Практические знания, применимые уже сегодня",
      tipCbtTitle: "КПТ – Изменение паттернов мышления",
      tipCbtDesc: "Научно доказанная когнитивно-поведенческая терапия при тревоге и депрессии.",
      tipWhenTitle: "Когда обращаться за помощью?",
      tipWhenDesc: "Если чувства грусти, тревоги или стресса длятся более двух недель – самое время обратиться.",
      tipBreathTitle: "Глубокое дыхание при тревоге",
      tipBreathDesc: "Вдох 4 секунды, задержка 4 секунды, выдох 6 секунд. Эта техника активирует парасимпатическую нервную систему.",
      tipMorningTitle: "Здоровое утро",
      tipMorningDesc: "Постоянный утренний распорядок – достаточный сон, лёгкие упражнения и завтрак – улучшает настроение.",
      tipSleepTitle: "Гигиена сна",
      tipSleepDesc: "Никаких экранов за полчаса до сна, постоянное время отхода ко сну и прохладная тёмная комната.",
      tipMindTitle: "Майндфулнес – 5 минут в день",
      tipMindDesc: "5 минут осознанного присутствия в день – концентрация на дыхании и ощущениях тела – снижает стресс.",
      // Filter panel
      filterReset: "Сброс",
      filterProfession: "Профессия",
      filterAllCities: "Все города",
      filterMaxBudget: "Макс. бюджет",
      // Professions
      profPsychologist: "Психолог",
      profPsychiatrist: "Психиатр",
      profPsychotherapist: "Психотерапевт",
      profSocialWorker: "Клинический соцработник",
      profCounselor: "Консультант",
      // Formats
      formatInPerson: "Лично",
      formatZoom: "Zoom",
      formatPhone: "Телефон",
      // HMOs
      hmoMaccabi: "Маккаби",
      hmoClalit: "Клалит",
      hmoMeuhedet: "Меухедет",
      hmoLeumit: "Леумит",
      hmoMenora: "Менора Мивтахим",
      hmoHarel: "Арель",
      hmoClal: "Клаль Битуах",
      hmoMigdal: "Мигдаль",
      hmoPhoenix: "Феникс",
      hmoAyalon: "Аялон",
      hmoPrivate: "Частный (без страховки)",
      // Languages
      langHebrew: "Иврит",
      langEnglish: "Английский",
      langArabic: "Арабский",
      langRussian: "Русский",
      langFrench: "Французский",
      langSpanish: "Испанский",
      langAmharic: "Амхарский",
      // Gender
      genderFemale: "Женский",
      genderMale: "Мужской",
      // Register Therapist form
      registerPhotoAlt: "Фото профиля",
      registerPhotoLabel: "Фото профиля",
      registerPhotoHint: "Профессиональное фото повышает доверие пациентов",
      registerUploadPhoto: "Загрузить фото",
      registerUploading: "Загружаю...",
      registerPhotoUploaded: "Фото успешно загружено",
      registerLicenseUploaded: "Документ успешно загружен ✓",
      registerFullName: "Полное имя",
      registerFullNamePlaceholder: "Д-р Иван Иванов",
      registerLicenseNumber: "Номер лицензии",
      registerProfession: "Профессия",
      registerSelectProfession: "Выберите профессию",
      registerAbout: "О себе",
      registerAboutPlaceholder: "Расскажите о своём подходе к терапии, опыте и специализациях...",
      registerCity: "Город",
      registerCityPlaceholder: "Тель-Авив",
      registerPrice: "Цена за сеанс (₪)",
      registerPhone: "Телефон",
      registerEmail: "Электронная почта",
      registerFormat: "Формат терапии",
      registerHmo: "Больничные кассы и страховые компании",
      registerTreatmentMethods: "Методы лечения",
      registerSpecializations: "Области терапии и специализации",
      registerLanguages: "Языки терапии",
      registerLicenseDoc: "Загрузить документ профессиональной лицензии (рекомендуется)",
      registerLicenseDocHint: "Загрузите сертификат, профессиональную лицензию или разрешение от компетентного органа.",
      registerReplaceFile: "Заменить файл",
      registerChooseFile: "Выбрать файл (PDF / Изображение)",
      registerFootnote: "Профиль будет опубликован только после проверки лицензии",
      registerRequiredFields: "Пожалуйста, заполните обязательные поля",
      // Accessibility Menu
      a11yMenuTitle: "Доступность – WCAG 2.1 AAA",
      a11yClose: "Закрыть меню доступности",
      a11yQuickProfiles: "Быстрые профили",
      a11ySeizureSafe: "Безопасно для эпилепсии",
      a11yVisionImpaired: "Нарушение зрения",
      a11yCognitive: "Когнитивный",
      a11yAdhd: "Дружественный ADHD",
      a11yKeyboard: "Клавиатурная навигация",
      a11yReset: "Сброс",
      a11yFontSize: "Размер текста",
      a11yDecrease: "Уменьшить",
      a11yIncrease: "Увеличить",
      a11yDecreaseLabel: "Уменьшить текст",
      a11yIncreaseLabel: "Увеличить текст",
      a11yDisplay: "Отображение",
      a11yHighContrast: "Высокий контраст",
      a11yInvertColors: "Инвертировать цвета",
      a11yGrayscale: "Оттенки серого",
      a11ySeizureSafeMode: "Режим безопасности эпилепсии",
      a11yReading: "Чтение",
      a11yReadableFont: "Читаемый шрифт (Arial)",
      a11yLineSpacing: "Увеличенный межстрочный интервал",
      a11yHighlightLinks: "Выделить ссылки",
      a11yNavMotor: "Навигация и моторика",
      a11yLargeCursor: "Большой курсор",
      a11yFocusHighlight: "Выделение фокуса",
      a11yStopAnimations: "Остановить анимации",
      a11yAdhdFriendly: "Режим ADHD",
      a11yResetAll: "Сбросить все настройки",
      a11yWcag: "Соответствует WCAG 2.1/2.2 AAA",
      a11yOn: "Вкл",
      a11yOff: "Выкл",
      a11yAriaLabel: "Меню доступности",
      a11yAriaDialog: "Параметры доступности",
    },
  };